/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-124319-gb801f1fe6d-20260503"
#endif /* AVUTIL_FFVERSION_H */
